openapi: 3.0.0
info:
  title: Manuscript API
  description: API per la gestione di manoscritti con RDF Turtle
  version: 1.0.0

servers:
  - url: https://api.example.org

paths:
  /manuscripts/{id}:
    get:
      summary: Ottieni un manoscritto
      description: Restituisce una risorsa Manuscript nel formato Turtle.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Dati del manoscritto in Turtle
          content:
            text/turtle:
              schema:
                $ref: "#/components/schemas/Manuscript"
              example: |
                @prefix ex: <http://example.org/schema/> .
                @prefix dcterms: <http://purl.org/dc/terms/> .

                <http://example.org/manuscripts/123> a ex:Manuscript ;
                    ex:title "Codex Vaticanus" ;
                    ex:description "Uno dei più antichi manoscritti della Bibbia" ;
                    ex:binding <http://example.org/bindings/leather-binding>,
                               <http://example.org/bindings/gold-embossed> ;
                    ex:extend <http://example.org/dimensions/25x30cm-800pages>,
                              <http://example.org/dimensions/folio-large> ;
                    ex:history <http://example.org/histories/vatican-discovery>,
                               <http://example.org/histories/medieval-restoration> ;
                    dcterms:bibliography <http://example.org/bibliographies/smith1990>,
                                        <http://example.org/bibliographies/jones2005> .
        "404":
          description: Manuscript non trovato

components:
  schemas:
    Manuscript:
      type: object
      properties:
        "@context":
          type: string
          example: "http://example.org/context"
        "@id":
          type: string
          format: uri
          example: "http://example.org/manuscripts/123"
        "@type":
          type: string
          example: "http://example.org/schema/Manuscript"
        title:
          type: string
          example: "Codex Vaticanus"
        description:
          type: string
          example: "Uno dei più antichi manoscritti della Bibbia"
        binding:
          type: array
          items:
            type: string
            format: uri
          example:
            - "http://example.org/bindings/leather-binding"
            - "http://example.org/bindings/gold-embossed"
        extend:
          type: array
          items:
            type: string
            format: uri
          example:
            - "http://example.org/dimensions/25x30cm-800pages"
            - "http://example.org/dimensions/folio-large"
        history:
          type: array
          items:
            type: string
            format: uri
          example:
            - "http://example.org/histories/vatican-discovery"
            - "http://example.org/histories/medieval-restoration"
        bibliography:
          type: array
          items:
            type: string
            format: uri
          example:
            - "http://example.org/bibliographies/smith1990"
            - "http://example.org/bibliographies/jones2005"
