openapi: 3.0.0
info:
  title: Manuscript API
  description: API per la gestione di manoscritti con RDF Turtle
  version: 1.0.0

servers:
  - url: https://api.example.org

paths:
  /manuscripts/{id}:
    get:
      summary: Ottieni un manoscritto
      description: Restituisce una risorsa Manuscript nel formato Turtle.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Dati del manoscritto in Turtle
          content:
            text/turtle:
              schema:
                $ref: "#/components/schemas/Manuscript"
              example: |
                @prefix ex: <http://example.org/schema/> .
                @prefix dcterms: <http://purl.org/dc/terms/> .

                <http://example.org/manuscripts/123> a ex:Manuscript ;
                    ex:title "Codex Vaticanus" ;
                    ex:description "Uno dei più antichi manoscritti della Bibbia" ;
                    ex:binding <http://example.org/bindings/leather-binding>,
                               <http://example.org/bindings/gold-embossed> ;
                    ex:extend <http://example.org/dimensions/25x30cm-800pages>,
                              <http://example.org/dimensions/folio-large> ;
                    ex:history <http://example.org/histories/vatican-discovery>,
                               <http://example.org/histories/medieval-restoration> ;
                    dcterms:bibliography <http://example.org/bibliographies/smith1990>,
                                        <http://example.org/bibliographies/jones2005> .
        "401":
          description: Non autorizzato - Autenticazione richiesta
          content:
            application/json:
              example:
                error: "Unauthorized"
                message: "Token non valido o mancante."
        "403":
          description: Accesso negato - Permessi insufficienti
          content:
            application/json:
              example:
                error: "Forbidden"
                message: "Non hai i permessi per accedere a questa risorsa."
        "404":
          description: Manuscript non trovato
          content:
            application/json:
              example:
                error: "Not Found"
                message: "Il manoscritto richiesto non esiste."

    post:
      summary: Crea un nuovo manoscritto
      description: Aggiunge un nuovo manoscritto alla collezione.
      requestBody:
        required: true
        content:
          text/turtle:
            schema:
              $ref: "#/components/schemas/Manuscript"
      responses:
        "201":
          description: Manuscript creato con successo
          content:
            application/json:
              example:
                message: "Manuscript creato con successo."
                id: "123"
        "401":
          description: Non autorizzato - Autenticazione richiesta
          content:
            application/json:
              example:
                error: "Unauthorized"
                message: "Token non valido o mancante."
        "403":
          description: Accesso negato - Permessi insufficienti
          content:
            application/json:
              example:
                error: "Forbidden"
                message: "Non hai i permessi per creare un manoscritto."

    put:
      summary: Aggiorna un manoscritto
      description: Sostituisce completamente un manoscritto esistente con una nuova versione.
      requestBody:
        required: true
        content:
          text/turtle:
            schema:
              $ref: "#/components/schemas/Manuscript"
      responses:
        "200":
          description: Manuscript modificato con successo
          content:
            application/json:
              example:
                message: "Manuscript aggiornato con successo."
        "401":
          description: Non autorizzato - Autenticazione richiesta
          content:
            application/json:
              example:
                error: "Unauthorized"
                message: "Token non valido o mancante."
        "403":
          description: Accesso negato - Permessi insufficienti
          content:
            application/json:
              example:
                error: "Forbidden"
                message: "Non hai i permessi per modificare questo manoscritto."
        "404":
          description: Manuscript non trovato
          content:
            application/json:
              example:
                error: "Not Found"
                message: "Il manoscritto richiesto non esiste."

    patch:
      summary: Modifica parzialmente un manoscritto
      description: Aggiorna alcuni campi di un manoscritto esistente.
      requestBody:
        required: true
        content:
          text/turtle:
            schema:
              $ref: "#/components/schemas/Manuscript"
      responses:
        "200":
          description: Manuscript modificato con successo
          content:
            application/json:
              example:
                message: "Manuscript aggiornato parzialmente con successo."
        "401":
          description: Non autorizzato - Autenticazione richiesta
          content:
            application/json:
              example:
                error: "Unauthorized"
                message: "Token non valido o mancante."
        "403":
          description: Accesso negato - Permessi insufficienti
          content:
            application/json:
              example:
                error: "Forbidden"
                message: "Non hai i permessi per modificare questo manoscritto."
        "404":
          description: Manuscript non trovato
          content:
            application/json:
              example:
                error: "Not Found"
                message: "Il manoscritto richiesto non esiste."

    delete:
      summary: Elimina un manoscritto
      description: Rimuove un manoscritto dalla collezione.
      responses:
        "204":
          description: Manuscript eliminato con successo
        "401":
          description: Non autorizzato - Autenticazione richiesta
          content:
            application/json:
              example:
                error: "Unauthorized"
                message: "Token non valido o mancante."
        "403":
          description: Accesso negato - Permessi insufficienti
          content:
            application/json:
              example:
                error: "Forbidden"
                message: "Non hai i permessi per eliminare questo manoscritto."
        "404":
          description: Manuscript non trovato
          content:
            application/json:
              example:
                error: "Not Found"
                message: "Il manoscritto richiesto non esiste."

components:
  schemas:
    Manuscript:
      type: object
      properties:
        "@context":
          type: string
          example: "http://example.org/context"
        "@id":
          type: string
          format: uri
          example: "http://example.org/manuscripts/123"
        "@type":
          type: string
          example: "http://example.org/schema/Manuscript"
        title:
          type: string
          example: "Codex Vaticanus"
        description:
          type: string
          example: "Uno dei più antichi manoscritti della Bibbia"
        binding:
          type: array
          items:
            type: string
            format: uri
          example:
            - "http://example.org/bindings/leather-binding"
            - "http://example.org/bindings/gold-embossed"
        extend:
          type: array
          items:
            type: string
            format: uri
          example:
            - "http://example.org/dimensions/25x30cm-800pages"
            - "http://example.org/dimensions/folio-large"
        history:
          type: array
          items:
            type: string
            format: uri
          example:
            - "http://example.org/histories/vatican-discovery"
            - "http://example.org/histories/medieval-restoration"
        bibliography:
          type: array
          items:
            type: string
            format: uri
          example:
            - "http://example.org/bibliographies/smith1990"
            - "http://example.org/bibliographies/jones2005"
