version: "3.7"
services:
  prism:
    image: stoplight/prism:4
    command: ["mock", "-p", "4010", "/openapi.json"]
    volumes:
      - ./openapi.json:/openapi.json
    ports:
      - "4010:4010"

  redoc:
    image: redocly/redoc
    ports:
      - "8080:80"
    volumes:
      - ./openapi.json:/usr/share/nginx/html/openapi.json
    environment:
      SPEC_URL: /openapi.json

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /openapi.json
    volumes:
      - ./openapi.json:/openapi.json
